/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as NewInvoiceRouteImport } from './routes/new-invoice'
import { Route as PortalLinksRouteImport } from './routes/portal-links'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const NewInvoiceRoute = NewInvoiceRouteImport.update({
  id: '/new-invoice',
  path: '/new-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLinksRoute = PortalLinksRouteImport.update({
  id: '/portal-links',
  path: '/portal-links',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/collections': typeof CollectionsRoute
  '/expenses': typeof ExpensesRoute
  '/forecast': typeof ForecastRoute
  '/health': typeof HealthRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/new-invoice': typeof NewInvoiceRoute
  '/portal-links': typeof PortalLinksRoute
  '/what-if': typeof WhatIfRoute
  '/portal/$token': typeof PortalTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/collections': typeof CollectionsRoute
  '/expenses': typeof ExpensesRoute
  '/forecast': typeof ForecastRoute
  '/health': typeof HealthRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/new-invoice': typeof NewInvoiceRoute
  '/portal-links': typeof PortalLinksRoute
  '/what-if': typeof WhatIfRoute
  '/portal/$token': typeof PortalTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/collections': typeof CollectionsRoute
  '/expenses': typeof ExpensesRoute
  '/forecast': typeof ForecastRoute
  '/health': typeof HealthRoute
  '/inventory': typeof InventoryRoute
  '/invoices': typeof InvoicesRoute
  '/new-invoice': typeof NewInvoiceRoute
  '/portal-links': typeof PortalLinksRoute
  '/what-if': typeof WhatIfRoute
  '/portal/$token': typeof PortalTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/ask'
    | '/audit'
    | '/collections'
    | '/expenses'
    | '/forecast'
    | '/health'
    | '/inventory'
    | '/invoices'
    | '/new-invoice'
    | '/portal-links'
    | '/what-if'
    | '/portal/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/ask'
    | '/audit'
    | '/collections'
    | '/expenses'
    | '/forecast'
    | '/health'
    | '/inventory'
    | '/invoices'
    | '/new-invoice'
    | '/portal-links'
    | '/what-if'
    | '/portal/$token'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/ask'
    | '/audit'
    | '/collections'
    | '/expenses'
    | '/forecast'
    | '/health'
    | '/inventory'
    | '/invoices'
    | '/new-invoice'
    | '/portal-links'
    | '/what-if'
    | '/portal/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AskRoute: typeof AskRoute
  AuditRoute: typeof AuditRoute
  CollectionsRoute: typeof CollectionsRoute
  ExpensesRoute: typeof ExpensesRoute
  ForecastRoute: typeof ForecastRoute
  HealthRoute: typeof HealthRoute
  InventoryRoute: typeof InventoryRoute
  InvoicesRoute: typeof InvoicesRoute
  NewInvoiceRoute: typeof NewInvoiceRoute
  PortalLinksRoute: typeof PortalLinksRoute
  WhatIfRoute: typeof WhatIfRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-invoice': {
      id: '/new-invoice'
      path: '/new-invoice'
      fullPath: '/new-invoice'
      preLoaderRoute: typeof NewInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal-links': {
      id: '/portal-links'
      path: '/portal-links'
      fullPath: '/portal-links'
      preLoaderRoute: typeof PortalLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AskRoute: AskRoute,
  AuditRoute: AuditRoute,
  CollectionsRoute: CollectionsRoute,
  ExpensesRoute: ExpensesRoute,
  ForecastRoute: ForecastRoute,
  HealthRoute: HealthRoute,
  InventoryRoute: InventoryRoute,
  InvoicesRoute: InvoicesRoute,
  NewInvoiceRoute: NewInvoiceRoute,
  PortalLinksRoute: PortalLinksRoute,
  WhatIfRoute: WhatIfRoute,
  PortalTokenRoute: PortalTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
